## Lab 1 - Python wprowadzenie
### Sieci Neuronowe w Automatyce

* informacje do poleceń bez odwołań do dokumentacji znajdują się w notebooku z wykładu (w1_python_wprowadzenie.ipynb)
* komórki mają postać tekstu (markdown) lub kodu
* Ctrl + MM (Esc + M jupyter lokalnie) przełącza w tryb tekstowy
* Ctrl + MY (Esc + Y jupyter lokalnie) przełącza w tryb kodu
* Komórkę wykonujemy wciskając Shift + Enter
* Po wykonaniu komórki drukowana jest wartość z ostatniej linii komórki (uwaga: operator "przypisania" = nic nie zwraca, więc nic się nie drukuje, jeśli w ostatniej linii mamy przypisanie
* Wydruk z dowolnego miejsca w kodzie można zrobić funkcją print()

### Część 1 - Podstawy (3 pkt.)

1.1 (0.25 pkt.) Zdefiniuj przykładowe zmienne różnych typów (int, float, string, lista, krotka, słownik), wydrukuj ich zawartość oraz typ (za pomocą funkcji type)

In [7]:
intt = 1
floatt = 0.01
stringg = "witek"
listaa = [1 ,1 ,2 ]
krotkaa = ( 1 ,2 ,3 , "ola")
slownikk = { "witold":3 , "jablonski":4}
print(type(intt))
print(type(floatt))
print(type(stringg))
print(type(listaa))
print(type(krotkaa))
print(type(slownikk))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'list'>
<class 'tuple'>
<class 'dict'>


1.2 (0.25 pkt.) Zdefiniuj listę pięciu liczb. Wydrukuj jej długość (funkcją len) i sumę (funkcją sum).

In [2]:
listaa = [ 1, 2, 3, 4, 5]
print(len(listaa))
print(sum(listaa))

5
15


1.3 (0.5 pkt.) Napisz instrukcję warunkową sprawdzającą czy dana liczba jest podzielna przez 2 (operator modulo to %)

In [8]:
if intt%2:
  print("niepodzielna")
else:
  print("podzielna")

niepodzielna


1.4 (1 pkt.) Zdefiniuj listę 5 liczb i utwórz słownik, zawierający liczby wystąpień elementów na liście. Np. dla listy [1, 2, 1, 3, 2] chcemy dostać {1: 2, 2: 2, 3: 1}. Wykorzystać pętlę for i funkcję get klasy dict z wartością domyślną 0.

In [10]:
lista = [ 1 ,2 , 4 ,5 ,2 ]
count = {}
for liczba in lista:
  count[liczba] = count.get(liczba, 0) + 1
print (count)

{1: 1, 2: 2, 4: 1, 5: 1}


1.5 (1 pkt.) Napisz funkcję sprawdzającą, czy dana liczba $n$ jest pierwsza. Funkcja powinna zwracać wartość logiczną. Należy sprawdzać, czy dana liczb dzieli się przez jakąś liczbę całkowitą z zakresu <2, $\sqrt{n}$>. Zaimportować bibliotekę math (import math) i wykorzystać math.sqrt

### Część 2 - NumPy (3.5 pkt.)

Żadne z zadań w tej częsci nie wymaga użycia pętli for.

2.1 (0.5 pkt.) Utwórz jednowymiarową macierz NumPy zawierającą liczby od 1 do 9 (łącznie z 9). Użyj np.arange. Zapisz tę macierz pod zmienną a. Wydrukuj.

Wybierz i wydrukuj elementy o indeksach od 2 do 5 (łącznie z elementem o indeksie 5).

In [22]:
import numpy as np
a = np.arange ( 1 , 10 ,1)
print(a)
print(a[1:5])

[1 2 3 4 5 6 7 8 9]
[2 3 4 5]


2.2 (0.5 pkt.) Utwórz macierz A, przekształcając macierz a do kształtu 3 x 3. Użyj funkcji reshape. Wydrukuj.

Wybierz drugą (o indeksie 1) kolumnę macierzy i wydrukuj.

In [25]:
A = a.reshape(3,3)
print (A)
print (A[:,1])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 5 8]


2.3 (0.5 pkt.) Utwórz macierz B o wymiarze 3 x 3 zawierającą same dwójki (np.ones i  mnożenie przez 2)

* Policz sumę i iloczyn macierzy A i B element po elemencie.
* Policz macierzowy iloczyn macierzy A i B
* Policz sinus każdego elementu macierzy A

In [33]:
B = np.ones((3,3)) * 2
print (B)
X = A + B
print (X)
X = A * B
print (X)
Sinn = np.sin(A)
print (Sinn)

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
[[ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]


2.4 (0.5 pkt.) Utwórz macierze c = np.array([[1], [2], [3]]) i  d = np.array([1, 2, 3]).

Jaki jest wyniki A + c i A + d? Dlaczego? Odpowiedź na pytanie dlaczego napisz w komórce typu markdown (Esc + M).

Dzien dobry, dodawanie zostało zastosowane dla kazdej kolumny i dla kazdego wiersza w zaleznosci od macierzy c i d


In [35]:
c = np.array([[1], [2], [3]])
d = np.array([1, 2, 3])
print(A)

print(c)
print(d)
print (A + c)
print (A + d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1]
 [2]
 [3]]
[1 2 3]
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


2.5 (0.5 pkt.) Utwórz macierz wartości logicznych wskazującą, które wartości macierzy A są większe od 4.

Użyj tej macierzy do wybrania tych elementów macierzy A, które są większe od 4.

2.6 (1 pkt.) Dla wartości x = np.arange(-5, 5, 1) i y = np.arange(-5, 5, 1). Utwórz siatkę zawierającą odległość od punktu (0, 0) dla każdego punktu. Zastosuj broadcasting. Nie stosuj pętli for.

In [ ]:
x = np.arange(-5, 5, 1)
y = np.arange(-5, 5, 1)


### Część 3 - Pandas (3.5 pkt.)

Biblioteka pandas jest narzędziem do przetwarzania danych tabelarycznych. Będziemy z niej korzystać w dalszych ćwiczeniach.

3.1 (0.5 pkt.) Zaimportuj bibliotekę pandas i nadaj jej alias pd.

Utwórz obiekt klasy DataFrame o nazwie df zawierający dane (wykorzystaj przykład (np. pierwszy) z dokumentacji https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html):

Dane z kolumny "Czas" podaj jako napisy, a dane z kolumn z temperaturą i ciśnieniem jako liczby.


| Czas               | Temperatura (°C) | Ciśnienie (Pa) |
|--------------------|------------------|----------------|
| 2024-10-14 08:00:00| 22.5             | 101325         |
| 2024-10-14 09:00:00| 23.0             | 101400         |
| 2024-10-14 10:00:00| 22.8             | 101350         |
| 2024-10-14 11:00:00| 23.2             | 101420         |

Wyświetl zawartość utworzonej zmiennej.

ValueError: DataFrame constructor not properly called!

3.2 (0.5 pkt.) Wybierz zawartość kolumny czas i wyświetl jej zawartość.
Kolumny wybieramy jako df[\<nazwa kolumny\>].

Zamień zawartość kolumny "Czas" na typ datetime (pd.to_datetime(\<wybrana kolumna\>)) i podstaw pod kolumnę "Czas"

3.3 (1 pkt.) Utwórz kolumnę "Temperatura (°C) (k-1)" zawierającą temperaturę z poprzedniej godziny. Uzyj funkcji shift (https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.shift.html).

3.4 (1.5 pkt.) Utwórz jeden wykres zawierający wartości z kolumn "Temperatura (°C)" i "Temperatura (°C) (k-1)" jako wykresy liniowe. Użyj biblioteki matplotlib. Dodaj opis osi i legendę.